config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tables#index'
  resources :tables, only: [:new, :create, :destroy]
  resources :customers, only: [:index, :new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :customers_tables
  has_many :tables, through: :customers_tables

  validates :name, presence: true
  validates :tel, presence: true
end

app/models/customers_table.rb
class CustomersTable < ApplicationRecord
  belongs_to :table
  belongs_to :customer
end

app/models/table.rb
class Table < ApplicationRecord
  belongs_to :user
  has_many :customers_tables
  has_many :customers, through: :customers_tables

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tables
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:edit, :update]


  def index
    @customers = Customer.where(user_id: current_user.id).where('tel LIKE(?) or day LIKE(?) or name LIKE(?)', "%#{params[:keyword]}%","%#{params[:keyword]}%","%#{params[:keyword]}%")
    respond_to do |format|
      format.html
      format.json
    end
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to root_path, notice: "予約を登録しました"
    else
      redirect_to new_customer_path, alert: "名前、もしくは電話番号が未入力です"
    end
  end

  def edit
  end

  def update
    if @customer.update(customer_params)
      redirect_to root_path, notice: "顧客情報を編集しました"
    else
      render :edit
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:name, :people, :tel, :day, :time, :text, { :table_ids => [] }).merge(user_id: current_user.id)
  end

  def set_customer
    @customer = Customer.find(params[:id])
  end
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController

  def index
    @table = Table.where(params[:customer_id])
  end

  def new
    @table = Table.new
  end

  def create
    @table = Table.new(table_params)
    if @table.save
      redirect_to root_path, notice: "テーブルを登録しました"
    else
      redirect_to new_table_path, alert: "テーブル名を入力してください"
    end
  end

  def destroy
    Table.find(params[:id]).destroy
    redirect_to root_path, notice: "予約を削除しました"
  end

  private
  def table_params
    params.require(:table).permit(:name).merge(user_id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/customers/edit.html.haml
.wrapper
  = render 'shared/header'
  .contents
    .title
      顧客編集
      %hr/
    .coment
      ・数字は半角で入力してください。<br>
      ・電話番号は(-)ハイフンを含めて入力してください。<br>
      ・予約日は西暦と月と日を(/)スラッシュで区切ってください。<br>
      ・テーブルを複数選択する場合はshiftキー(または⌘キー)を押しながら選択してください。<br>
      ・テーブルの選択を解除する場合は⌘キーを押しながら選択済みのテーブルをクリックしてください。

    .form
      = form_for [@customer]  do |f|
        .new-input
          = f.label :name, "名前", class: "label"
          = f.text_field :name, class: "input-box", placeholder: "例: サトウ"
          = f.label :people, "人数", class: "label"
          = f.number_field :people, class: "input-box", placeholder: "例: 12"
          = f.label :tel, "電話番号", class: "label"
          = f.text_field :tel, class: "input-box", placeholder: "例: 123-4567-8910"
          = f.label :day, "日程", class: "label"
          = f.date_field :day, class: "input-box", value: @customer.day
          = f.label :time, "時間", class: "label"
          = f.time_field :time, class: "input-box", value: @customer.time
          = f.label :table_ids, "テーブル", class: "label"
          = f.collection_select :table_ids, Table.all, :id, :name,{}, {multiple: true}
          = f.text_area :text, class: "input-area", placeholder: "備考欄"
          = f.submit '更新', class: "submit-btn"

app/views/customers/index.html.haml
.wrapper
  = render 'shared/header'
  .contents
    .form
      .form_title
        顧客情報検索
      .form_search-box
        = form_tag('/customers', method: :get, id: "search_customer")  do
          = text_field_tag :search,"",name: "keyword",placeholder: "電話番号を入力してください",class: "customer-search" 
    .message
      ・電話番号(例: 123-4567-8910)または名前(例: サトウ)を入力することで顧客情報を検索できます。<br>
      ・予約日(例: 1111-11-11)を入力することで検索したい日程の予約を一覧表示できます。
    .customers
      - @customers.each do |customer|
        .customer
          .customer_name
            = customer.name + "様"
          .customer_people
            = customer.people + "名"
          .customer_tel
            = customer.tel
          .customer_day
            = customer.day
          .customer_time
            = customer.time
          .customer_text
            = customer.text
          .customer_edit
            = link_to '編集', "/customers/#{customer.id}/edit", method: :get, class: "customer_edit_btn"

app/views/customers/new.html.haml
.wrapper
  = render 'shared/header'
  .contents
    .title
      予約登録
      %hr/
    .coment
      ・数字は半角で入力してください。
      %br
      ・電話番号は(-)ハイフンを含めて入力してください。
      %br
      ・予約日は西暦と月と日を(/)スラッシュで区切ってください。
      %br
      ・テーブルを複数選択、解除する場合は⌘キーを押しながら選択してください。
    .form
      = form_for [@customer]  do |f|
        .new-input
          = f.label :name, "名前", class: "label"
          %span
            ※必須
          = f.text_field :name, class: "input-box", placeholder: "例: サトウ"
          = f.label :people, "人数", class: "label"
          = f.number_field :people, class: "input-box", placeholder: "例: 12"
          = f.label :tel, "電話番号", class: "label"
          %span
            ※必須
          = f.text_field :tel, class: "input-box", placeholder: "例: 123-4567-8910"
          = f.label :day, "日時", class: "label"
          = f.date_field :day, class: "input-box", placeholder: "予約日"
          = f.label :time, "時間", class: "label"
          = f.time_field :time, class: "input-box", placeholder: "予約時間"
          = f.label :table_ids, "テーブル", class: "label"
          = f.collection_select :table_ids, Table.all, :id, :name,{}, {multiple: true}
          = f.text_area :text, class: "input-area", placeholder: "備考欄"
          = f.submit '登録', class: "submit-btn"

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FloorManagement
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script(src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js")

  %body
    = render 'layouts/notifications'
    = yield

app/views/shared/_header.html.haml
.header
  = link_to "Floor Management",root_path,class: "header_logo"
  .header_menu
    =link_to "テーブル登録",new_table_path, class: "header_menu_new"
    =link_to "テーブル一覧",root_path, class: "header_menu_index"
    =link_to "当日予約",new_customer_path, class: "header_menu_reservation" 
    =link_to "顧客情報",customers_path, class: "header_menu_customers"
  .header_edit-user
    =link_to"ログアウト", destroy_user_session_path, method: :delete, class: "header_edit-user__btn"

app/views/tables/_table.html.haml
.table_body{id: "customer-#{table.id}"}
  %input{name: "table[customer_ids][]", type: "hidden", value: "#{table.id}"}/
  .table_body_customer-name
    =table.name + "様"
  .table_body_people
    =table.people + "名"
  .table_body_tel
    =table.tel
  .table_body_day
    =table.day
  .table_body_time
    =table.time
  .table_body_text
    =table.text
  = link_to '予約編集', "/customers/#{table.id}/edit", method: :get, class: "table_body_reservation"

app/views/tables/index.html.haml
.wrapper
  = render 'shared/header'
  .contents
    .tables
      %button.table_reset
        着席状態を全て解除
      - current_user.tables.each do |table|
        .table{id: "table-#{table.id}"}
          %input{name: "table[customer_ids][]", type: "hidden", value: "#{table.id}"}/
          %input{name: "bgcolor",type: "checkbox", value: "lightpink", id: "#{table.id}", class: "table_check"}/
          .table_name
            =table.name
          .table_delete
            =link_to 'テーブル削除', "/tables/#{table.id}", method: :delete, class: "table_delete_btn"
          = render partial: "table", collection: table.customers

app/views/tables/new.html.haml
.wrapper
  = render 'shared/header'
  .contents
    .title
      テーブル登録
      %hr/
    .form
      = form_for [@table]  do |f|
        .new-input
          = f.text_field :name, class: "input-box", placeholder: "テーブル名", id: "name"
          = f.submit '登録', class: "submit-btn"